{{- if .Values.monitoring.serviceMonitor.enabled -}}
{{- $fullname := include "shclop.fullname" . -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullname }}-backend
  labels:
    {{- include "shclop.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: http
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      path: /metrics
  selector:
    matchLabels:
      {{- include "shclop.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
