{{- $fullname := include "shclop.fullname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullname }}-backend
  labels:
    {{- include "shclop.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
