{{- $fullname := include "shclop.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-backend
  labels:
    {{- include "shclop.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- if or .Values.service.annotations (and .Values.service.prometheusScrape (not .Values.monitoring.serviceMonitor.enabled)) }}
  annotations:
    {{- if and .Values.service.prometheusScrape (not .Values.monitoring.serviceMonitor.enabled) }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.port | quote }}
    prometheus.io/path: "/metrics"
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "shclop.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
